# Generated by Django 4.1.5 on 2023-01-28 18:25

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Soldier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.CharField(max_length=50, verbose_name='Rank')),
                ('first_name', models.CharField(max_length=100, verbose_name='Name')),
                ('last_name', models.CharField(max_length=100, verbose_name='Last name')),
            ],
            options={
                'ordering': ['rank', 'first_name', 'last_name'],
            },
        ),
        migrations.CreateModel(
            name='Weapon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('country', models.CharField(max_length=50, verbose_name='Country')),
                ('description', models.TextField(help_text='Weapon description', max_length=1000, verbose_name='Description')),
            ],
        ),
        migrations.CreateModel(
            name='WeaponUnit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Unique ID of a weapon', primary_key=True, serialize=False)),
                ('due_back', models.DateField(blank=True, null=True, verbose_name='Will be available')),
                ('status', models.CharField(blank=True, choices=[('t', 'Taken'), ('a', 'Available'), ('r', 'Reserved')], default='a', help_text='Status', max_length=1)),
                ('weapon', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='weaponry.weapon')),
            ],
            options={
                'ordering': ['due_back'],
            },
        ),
    ]
