# Generated by Django 4.1.5 on 2023-01-29 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weaponry', '0002_soldier_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='weapon',
            name='cover',
            field=models.ImageField(null=True, upload_to='covers', verbose_name='Cover'),
        ),
        migrations.AlterField(
            model_name='soldier',
            name='description',
            field=models.TextField(default='', max_length=2000, verbose_name='Description'),
        ),
    ]
