# Generated by Django 4.1.5 on 2023-01-29 22:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weaponry', '0004_weaponunit_reader'),
    ]

    operations = [
        migrations.RenameField(
            model_name='weaponunit',
            old_name='reader',
            new_name='operator',
        ),
    ]
