# Generated by Django 4.1.5 on 2023-01-30 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weaponry', '0005_rename_reader_weaponunit_operator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weaponunit',
            name='status',
            field=models.CharField(blank=True, choices=[('t', 'Taken'), ('a', 'Available')], default='a', help_text='Status', max_length=1),
        ),
    ]
