# Generated by Django 4.1.5 on 2023-01-30 13:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('weaponry', '0007_alter_weaponunit_operator'),
    ]

    operations = [
        migrations.AddField(
            model_name='soldier',
            name='has_weapon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='weaponry.weaponunit'),
        ),
    ]
