# Generated by Django 4.1.5 on 2023-01-30 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weaponry', '0008_soldier_has_weapon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='soldier',
            name='has_weapon',
        ),
    ]
