# Generated by Django 4.1.5 on 2023-01-31 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weaponry', '0010_videos'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Videos',
        ),
    ]
