# Generated by Django 4.1.5 on 2023-01-31 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weaponry', '0013_soldier_assigned_weapons_alter_soldier_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='soldier',
            name='assigned_weapons',
        ),
    ]
